SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
SRC="$SCRIPT_DIR/../epx-flags-resolver/epx-flags-resolver-lib/src/main/java"
DST="$SCRIPT_DIR/openfeature-provider-local/src/main/java"
cd "$SRC"

copy_class() {
  rsync -R "${1//.//}.java" "$DST"
}

# copy classes from epx-flags-resolver-lib
cd "$SCRIPT_DIR/../epx-flags-resolver/epx-flags-resolver-lib/src/main/java"
copy_class "com.spotify.confidence.flags.resolver.AccountResolver"
copy_class "com.spotify.confidence.flags.resolver.domain.Account"
copy_class "com.spotify.confidence.flags.resolver.domain.AccountClient"
copy_class "com.spotify.confidence.flags.resolver.domain.AccountState"
copy_class "com.spotify.confidence.flags.resolver.domain.AssignmentMatch"
copy_class "com.spotify.confidence.flags.resolver.domain.FallthroughRule"
copy_class "com.spotify.confidence.flags.resolver.domain.Region"
copy_class "com.spotify.confidence.flags.resolver.domain.ResolvedValue"
copy_class "com.spotify.confidence.flags.resolver.EvalUtil"
copy_class "com.spotify.confidence.flags.resolver.exceptions.BadRequestException"
copy_class "com.spotify.confidence.flags.resolver.exceptions.InternalServerException"
copy_class "com.spotify.confidence.flags.resolver.materialization.MaterializationInfo"
copy_class "com.spotify.confidence.flags.resolver.materialization.MaterializationStore"
copy_class "com.spotify.confidence.flags.resolver.MaterializationsHelper"
copy_class "com.spotify.confidence.flags.resolver.Metrics"
copy_class "com.spotify.confidence.flags.resolver.Randomizer"
copy_class "com.spotify.confidence.flags.resolver.ResolveFlagListener"
copy_class "com.spotify.confidence.flags.resolver.FlagResolverService"
copy_class "com.spotify.confidence.flags.resolver.domain.FlagToApply"
copy_class "com.spotify.confidence.flags.resolver.FlagLogger"
copy_class "com.spotify.confidence.flags.resolver.ResolveTokenConverter"

# copy classes from epx-target-lib
cd "$SCRIPT_DIR/../epx-target-lib/src/main/java"
copy_class "com.spotify.confidence.target.Expr"
copy_class "com.spotify.confidence.target.ExprNormalizer"
copy_class "com.spotify.confidence.target.TargetingExpr"
copy_class "com.spotify.confidence.target.Targetings"
copy_class "com.spotify.confidence.target.Util"
copy_class "com.spotify.confidence.target.value.Eq"
copy_class "com.spotify.confidence.target.value.Ord"
copy_class "com.spotify.confidence.target.value.SemanticVersion"