package com.spotify.confidence;

public enum ErrorType {
  FLAG_NOT_FOUND,
  INVALID_VALUE_TYPE,
  INVALID_VALUE_PATH,
  INVALID_CONTEXT,
  INTERNAL_ERROR,
  NETWORK_ERROR,
  PARSE_ERROR,
  PROVIDER_NOT_READY
}
